#!/bin/sh

src="$1"
out="$2"

# 本当に効果あるのか?
# OpenMP版ImageMagickの高負荷問題の最も簡単な対処法:ImageMagick:Technical tips:Media hub - http://tech.clickyourstyle.com/articles/194
export OMP_NUM_THREADS=1


# Kobo Aura One
WIDTH=1404
HEIGHT=1872

# Kobo Aura
# WIDTH=758
# HEIGHT=1014

SIZE="${WIDTH}x${HEIGHT}"

# ノイズに対する感度
FUZZ='50%'

convert \
  -fuzz "$FUZZ" -trim \
  -bordercolor white \
  -border 40x40 \
  -gravity center \
  -resize "$SIZE" -page "$SIZE" -extent "$SIZE" \
  -threshold 50000 \
  "$src" "$out"


# スキャナで自炊した画像をキンドル向けにImageMagickで最適化してみる - http://netbuffalo.doorblog.jp/archives/4033031.html
